// @generated by the Octelium API generator. DO NOT EDIT.

#![doc = include_str!("../README.md")]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// Re-exports of the runtime crates the generated code is built against.
///
/// Depending on these through `octelium-apis` keeps a dependent's versions
/// in lockstep with the generated code.
pub use prost;
pub use prost::bytes;
pub use prost_types;
pub use tonic;

pub mod octelium {
    pub mod api {
        pub mod main {
            pub mod auth {
                pub mod v1 {
                    include!("gen/octelium.api.main.auth.v1.rs");
                }
            }
            pub mod cordium {
                pub mod v1 {
                    include!("gen/octelium.api.main.cordium.v1.rs");
                }
            }
            pub mod core {
                pub mod v1 {
                    include!("gen/octelium.api.main.core.v1.rs");
                }
            }
            pub mod meta {
                pub mod v1 {
                    include!("gen/octelium.api.main.meta.v1.rs");
                }
            }
            pub mod user {
                pub mod v1 {
                    include!("gen/octelium.api.main.user.v1.rs");
                }
            }
        }
    }
}

/// The main Cluster APIs, named as in every other Octelium SDK.
pub mod main {
    /// The `octelium.api.main.auth.v1` protobuf package.
    pub use crate::octelium::api::main::auth::v1 as authv1;
    /// The `octelium.api.main.cordium.v1` protobuf package.
    pub use crate::octelium::api::main::cordium::v1 as cordiumv1;
    /// The `octelium.api.main.core.v1` protobuf package.
    pub use crate::octelium::api::main::core::v1 as corev1;
    /// The `octelium.api.main.meta.v1` protobuf package.
    pub use crate::octelium::api::main::meta::v1 as metav1;
    /// The `octelium.api.main.user.v1` protobuf package.
    pub use crate::octelium::api::main::user::v1 as userv1;
}

pub use main::{authv1, cordiumv1, corev1, metav1, userv1};
